rand.2000 <- rlnorm(2000,2.5,0.7 ) 
hist(rand.2000, breaks = 50, col ="blue", las = 1, main = "")

worms <- read.table(file="worms.csv", header = TRUE, sep=",")

worms[c(1,5)]
worms[2:3]
damp <- subset(worms[2:3], worms$Damp == "FALSE")
dev.new()
plot(worms$Soil.pH, worms$Worm.density,las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16)
abline(lm(worms$Worm.density ~ worms$Soil.pH), lty=2, col="blue")
pdf(file="C:/Users/uma/Desktop/R/SEYI/TestProjectSEYI2/AmbatiScatter.pdf", height = 7)
plot(worms$Soil.pH, worms$Worm.density,las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16)
abline(lm(worms$Worm.density ~ worms$Soil.pH), lty=2, col="blue")

dev.new()
pdf(file="C:/Users/uma/Desktop/R/SEYI/TestProjectSEYI2/AmbatiScatter2.pdf", height = 7)
plot(worms$Soil.pH, worms$Worm.density,las = 1, xlab = "soil pH", ylab = "Worm Density", type ="n")
points(worms$Soil.pH[worms$Vegetation=="Arable"],worms$Worm.density[worms$Vegetation=="Arable"] ,col="blue", pch=16)
points(worms$Soil.pH[worms$Vegetation=="Grassland"],worms$Worm.density[worms$Vegetation=="Grassland"] ,col="green", pch=16)
points(worms$Soil.pH[worms$Vegetation=="Meadow"],worms$Worm.density[worms$Vegetation=="Meadow"] ,col="pink", pch=16)
points(worms$Soil.pH[worms$Vegetation=="Orchard"],worms$Worm.density[worms$Vegetation=="Orchard"] ,col="red", pch=16)
points(worms$Soil.pH[worms$Vegetation=="Scrub"],worms$Worm.density[worms$Vegetation=="Scrub"] ,col="brown", pch=16)
legend(3.5,8,legend = c("Arable", "Grassland", "Meadow", "Orchard", "Scrub"),col=c("blue","green","pink","red","brown"), pch=16)

dev.new(width = 4, height= 5)
pdf(file="C:/Users/uma/Desktop/R/SEYI/TestProjectSEYI2/AmbatiScatter3.pdf", onefile = TRUE)
par(mfrow=c(3,2))
xlim <- range(worms$Soil.pH)
ylim <-range(worms$Worm.density)
plot(worms$Soil.pH, worms$Worm.density,las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16, main = "All Types", xlim = xlim, ylim=ylim)
plot(worms$Soil.pH[worms$Vegetation=="Arable"], worms$Worm.density[worms$Vegetation=="Arable"],las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16, main = "Arable", xlim = xlim, ylim=ylim, col ="blue")
plot(worms$Soil.pH[worms$Vegetation=="Grassland"], worms$Worm.density[worms$Vegetation=="Grassland"],las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16, col="green", main = "Grassland", xlim = xlim, ylim=ylim)
plot(worms$Soil.pH[worms$Vegetation=="Meadow"], worms$Worm.density[worms$Vegetation=="Meadow"],las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16, col="pink", main = "Meadow", xlim = xlim, ylim=ylim)
plot(worms$Soil.pH[worms$Vegetation=="Orchard"], worms$Worm.density[worms$Vegetation=="Orchard"],las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16, col="red", main = "Orchard", xlim = xlim, ylim=ylim)
plot(worms$Soil.pH[worms$Vegetation=="Scrub"], worms$Worm.density[worms$Vegetation=="Scrub"],las = 1, xlab = "soil pH", ylab = "Worm Density", pch=16, col="brown", main = "Scrub", xlim = xlim, ylim=ylim)
dev.off()
